spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:consulta_cep_db
    username: postgres
    password: XXXI.X.MMXVII
  profiles:
    hikari:
      maximum-pool-size: 10
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          url: jdbc:postgresql://postgresql:5432/consulta_cep_db
  logging:
    level:
      org:
        springframework:
          orm:
            jpa: DEBUG
        hibernate:
          SQL: DEBUG
          type: TRACE

server:
  port: 8081